#!/bin/bash

function _update_ps1() {
    PS1="$(powerline-shell $?)"
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

if [ -f ~/.bashrc ]; then
    # This script only support gnu sed
    . ~/.bashrc
fi
. ~/.bash/myenv

