#!/bin/bash
eval "$(rbenv init -)"

function _update_ps1() {
    PS1="$(powerline-shell $?)"
}

. ~/.bash/myenv

PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"

# add user path
PATH=~/bin:~/.local/bin:${PATH}
export PATH
