#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    # enable_tabline_filetype_icon = true
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    enable_vimfiler_gitstatus = true
    bootstrap_before = "config#before"


# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "nil"
  auto_completion_tab_key_behavior = "smart"
  auto_completion_delay = 200
  auto_completion_complete_with_key_sequence = "nil"
  auto_completion_complete_with_key_sequence_delay = 0.1

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

# Enable Python
[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#json"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "VersionControl"

[[custom_plugins]]
    name = "machakann/vim-highlightedyank"
    merged = false
