---
- name: Install global Composer packages.
  composer:
    command: "{{ (item.state | default('present') == 'absent') | ternary('remove', 'require') }}"
    arguments: "{{ item.name | default(item) }} {{ item.version | default('@stable') }}"
    # Ansible 2.4 supports `global_command` making `working_dir` optional.
    working_dir: "{{ lookup('env', 'COMPOSER_HOME') | default('~/.composer', true) }}"
  with_items: "{{ composer_packages }}"

- name: Install global NPM packages.
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ npm_packages }}"

- name: Install user Ruby gems.
  gem:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    #  user_install: yes
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ gem_packages }}"
  become: yes

- name: Install global Pip packages.
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
    #extra_args: "--user"
  with_items: "{{ pip_packages }}"
  become: yes

- name: Apply go get constabulary/gb.
  command: go get -u {{ item }}
  with_items: "{{ go_repos }}"
  environment:
    GOPATH: '/home/{{ ansible_user_id }}/go'

- name: Ensure directory exists.
  file:
    path: "{{ item }}"
    state: directory
  with_items:
      - ~/.bash
      - ~/.config/nvim
      - ~/.config/nvim/mysnippets
      - ~/.local/share/fonts
      - ~/.local/bin
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.16.1/docker-compose-Linux-x86_64
    dest: ~/.local/bin/docker-compose
    mode: 0555

- name: Install Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf
    dest: ~/.local/share/fonts/DroidSansMonoNerdFontComplete.otf
    mode: 0444


- name: Copy files
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
  with_items:
      - { src: "bash_profile", dest: "~/.bash_profile" }
      - { src: "myalias", dest: "~/.bash/myalias" }
      - { src: "myenv", dest: "~/.bash/myenv" }
      - { src: "init.vim", dest: "~/.config/nvim/init.vim" }
      - { src: "markdown.snip", dest: "~/.config/nvim/mysnippets/markdown.snip" }
      - { src: "powerline-shell.json", dest: "~/.powerline-shell.json" }
      - { src: "tmux.conf", dest: "~/.tmux.conf" }
  become: yes
  become_user: "{{ ansible_user_id }}"
