# Install apt keys and repositories
- apt_key:
    url: '{{ item }}'
  with_items: '{{ apt_key_urls }}'
  become: true

- apt_key:
    keyserver: '{{ item.keyserver }}'
    id: '{{ item.id }}'
  with_items: '{{ apt_key_ids }}'
  become: true

- apt_repository:
    repo: '{{ item }}'
  with_items: '{{ apt_repositories }}'
  become: true

# Remove apt packages
- name: Remove apt packages
  apt:
    name: '{{ apt_packages_remove }}'
    update_cache: no
    state: absent
    #  with_items: '{{ apt_packages_remove }}'
  become: true


# Install apt packages
- name: Install apt packages
  apt:
    name: '{{ apt_packages }}'
    update_cache: yes
    state: present
    #with_items: '{{ apt_packages }}'
  become: true

# Install deb packages from uris
- name: check if deb packages already installed
  shell: dpkg -s '{{ item.name }}' | grep 'install ok installed' || true
  with_items: '{{ deb_uris }}'
  register: deb_uris_check_result

- name: install missing deb packages
  apt:
    deb: '{{ item.1.uri }}'
  with_indexed_items: '{{ deb_uris }}'
  when: deb_uris_check_result.results[{{ item.0 }}].stdout == ""
  become: true
